apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.nginxAppName }}
  name: {{ template "teleport.namespace" . }}-{{ .Values.nginxAppName }}
  namespace: {{ template "teleport.namespace" . }}
imagePullSecrets:
- name: {{ .Values.vaultCommon.imagepullsecret.name }}
