apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nginxAppName }}
  name: {{ template "teleport.namespace" . }}-{{ .Values.nginxAppName }}-backend
  namespace: {{ template "teleport.namespace" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ .Values.nginxAppName }}
    component: default-backend
  sessionAffinity: None
  type: ClusterIP
