apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nginxAppName }}
  name: {{ template "teleport.namespace" . }}-{{ .Values.nginxAppName }}
  namespace: {{ template "teleport.namespace" . }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: httpsp
    port: 3129
    protocol: TCP
    targetPort: httpsp
  selector:
    app: {{ .Values.nginxAppName }}
  sessionAffinity: None
  type: LoadBalancer
