---
{{- $imagePullSecretName := .Values.vaultCommon.imagepullsecret.name }}
{{- $imagePullType := .Values.vaultCommon.imagepullsecret.type }}
{{- $imagePullKeys := .Values.vaultCommon.imagepullsecret.keys }}
{{- $imagePullPath := .Values.vaultCommon.imagepullsecret.path }}
{{- $githubName := .Values.vaultCommon.github.name }}
{{- $githubType := .Values.vaultCommon.github.type }}
{{- $githubKeys := .Values.vaultCommon.github.keys }}
{{- $githubPath := .Values.vaultCommon.github.path }}
{{- $svcuserName := .Values.vaultCommon.svcuser.name }}
{{- $svcuserType := .Values.vaultCommon.svcuser.type }}
{{- $svcuserPath := .Values.vaultCommon.svcuser.path }}

apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  name: {{ template "teleport.name" . }}-tls-web
  namespace: {{ .Release.Namespace }}
spec:
  path: "/certs/csp-cert"
  secretName: {{ template "teleport.name" . }}-tls-web
  secrets:
    csp: VAULT
  type: kubernetes.io/tls

---

apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  labels:
    app: {{ template "teleport.name" . }}
  name: {{ $imagePullSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  path: {{ tpl $imagePullPath . }}
  secretName: {{ $imagePullSecretName }}
  secrets:
    {{- range $imagePullKeys }}
    {{ . }}: VAULT
    {{- end }}
  type: {{ $imagePullType }}

---

apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  labels:
    app: {{ template "teleport.name" . }}
  name: {{ $githubName }}
  namespace: {{ .Release.Namespace }}
spec:
  path: {{ tpl $githubPath . }}
  secretName: {{ $githubName }}
  secrets:
    {{- range $githubKeys }}
    {{ . }}: VAULT
    {{- end }}
  type: {{ $githubType }}

---

apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  labels:
    app: {{ template "teleport.name" . }}
  name: {{ $svcuserName }}
  namespace: {{ .Release.Namespace }}
spec:
  path: {{ tpl $svcuserPath . }}
  secretName: {{ $svcuserName }}
  secrets:
    svcUserName: VAULT
    svcUserPass: VAULT
  type: {{ $svcuserType }}

---
